### ISSUE TITLE
Lazy Polars backend functionality

### ISSUE THREAD

**Issue by cigrainger** [elixir-nx/explorer#227]
This issue tracks the implementation for full backend functionality for lazy Polars. The intent is to enable splitting things up more easily.

## IO read

- [x] `from_csv` (#451)
- [x] `load_csv` (#451)
- [x] `from_parquet` (#451)
- [x] `load_parquet` (#451)
- [x] `from_ipc` (#451)
- [x] `load_ipc` (#451)
- [x] `from_ndjson` (#451)
- [x] `load_ndjson` (#451)
- [x] `load_ipc_stream` (b326afd48)

PS: `from_ipc_stream` for the Lazy backend is not possible because is not available in Polars. 

## IO write

- [x] Certain IO write operations can be done lazily for streaming: https://genserver.social/notice/AQn5LNxxRIfvNvvkNE - we need to investigate which and break it down
- [x] `to_parquet` (#496) 
- [x] `to_ipc` (#497) - available only in main branch of Polars 
- [x] `to_ipc_stream` (#497) - It's not streamable, even so the name contains "stream". `collect() |> write()`
- [x] `to_csv` (#497) - It's not streamable. `collect() |> write()`
- [x] `to_ndjson` (#497) -  It's not streamable. `collect() |> write()`

## Conversion

- [x] `lazy` (#202)
- [x] `to_lazy` (#202)
- [x] `collect` (#202)

## Introspection

- [x] `names` (#202)
- [x] `dtypes` (#202)
- [x] `shape` (#497)
- [x] `n_rows` (#497)
- [x] `n_columns` (#202)

## Single table verbs

- [x] `head` (#202)
- [x] `tail` (#202)
- [x] `select` (#202)
- [x] `filter` (#476)
- [x] `mutate`
- [x] `arrange`
- [x] `distinct`
- [x] `rename` (#488)
- [x] `dummies` (#497)
- [x] `sample` (#497) - this one may be possible to implement, but not sure how.
- [x] `pull` (#497)
- [x] `slice` (#450)
- [x] `drop_nil` (#488)
- [x] `pivot_wider` (#497)
- [x] `pivot_longer` (#488)
- [x] `group_by` (#202)
- [x] `ungroup` (#202)
- [x] `summarise`

## Two or more table verbs

- [x] `join` (#491)
- [x] `concat_rows` (#492)
- [x] `concat_columns` (#492)

**Comment by josevalim** [comment]
Regarding the IO functions, only half of them need to be implemented, right?

**Comment by josevalim** [comment]
All functions not listed here should raise when invoked saying the lazy operation is not allowed.

**Comment by philss** [comment]
FYI I'm working on the IO functions of this issue :)

**Comment by josevalim** [comment]
FWIW, we decided to focus on the non-grouped versions. We will support grouped ones later.

**Comment by philss** [comment]
I created #498 to track the groups operations.

I'm closing this issue, since most of the functions were implemented or are explicitly raising error now.
